#CIRCUITPY_WIFI_SSID = "FX2000-8ADA"
#CIRCUITPY_WIFI_PASSWORD = "45f48e6f"
CIRCUITPY_WIFI_SSID = "Radant"
CIRCUITPY_WIFI_PASSWORD = "poopbuttforever0816"
ADAFRUIT_AIO_USERNAME = "eradant"
ADAFRUIT_AIO_KEY = "aio_MzQi31LhdOx0ICED203104bAa1mx"